services:
  - type: web
    name: tablero-dh
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: SQL_PASS
        value: DHsql1234
      - key: DASHBOARD_PASS
        value: dh2026
      - key: NODE_ENV
        value: production
